import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F5F6FA" },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 16,
    backgroundColor: "#FFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  headerTitle: { fontSize: 24, fontWeight: "700", color: "#1A1A1A" },
  complaintList: { padding: 16 },
  complaintCard: {
    backgroundColor: "#FFF",
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    elevation: 2,
  },
  complaintTitle: { fontSize: 16, fontWeight: "600", color: "#1A1A1A" },
  complaintDate: { fontSize: 14, color: "#A0A0A0", marginTop: 4 },
  complaintStatus: { fontSize: 14, color: "#FFA726", marginTop: 4 },
  emptyContainer: { flex: 1, justifyContent: "center", alignItems: "center" },
  emptyText: { fontSize: 18, color: "#A0A0A0", marginTop: 16 },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#FFF",
    borderRadius: 8,
    width: "90%",
    maxHeight: "80%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  modalTitle: { fontSize: 20, fontWeight: "700", color: "#1A1A1A" },
  modalBody: { padding: 12 },
  modalDetail: { fontSize: 16, color: "#1A1A1A", marginBottom: 8 },
  modalLabel: { fontSize: 16, fontWeight: "600", color: "#1A1A1A", marginTop: 8 },
  modalText: { fontSize: 14, color: "#666", marginBottom: 8 },
  imageList: { marginBottom: 12 },
  modalImage: { width: 100, height: 100, borderRadius: 8, marginRight: 8 },
  imageContainer: { position: "relative", marginRight: 8 },
  imagePreview: { width: 80, height: 80, borderRadius: 8 },
  removeButton: { position: "absolute", top: -5, right: -5 },
  imagePickerButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F0F0F0",
    padding: 10,
    borderRadius: 8,
    marginBottom: 12,
  },
  imagePickerText: { fontSize: 14, color: "#007AFF", marginLeft: 8 },
  input: {
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 8,
    padding: 10,
    fontSize: 14,
    marginBottom: 12,
    minHeight: 50,
    textAlignVertical: "top",
  },
  submitButton: {
    backgroundColor: "#6B48FF",
    padding: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  submitButtonText: { fontSize: 16, color: "#FFF", fontWeight: "600" },
});
  export default styles;