import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#F5F6FA" },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      padding: 16,
      backgroundColor: "#FFF",
      borderBottomWidth: 1,
      borderBottomColor: "#E0E0E0",
    },
    headerTitle: { fontSize: 24, fontWeight: "700", color: "#1A1A1A" },
    searchContainer: {
      flexDirection: "row",
      alignItems: "center",
      margin: 16,
      backgroundColor: "#FFF",
      borderRadius: 8,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: "#E0E0E0",
    },
    searchIcon: { marginRight: 8 },
    searchInput: { flex: 1, fontSize: 16, paddingVertical: 8 },
    productList: { padding: 16 },
    productCard: {
      backgroundColor: "#FFF",
      borderRadius: 8,
      padding: 12,
      marginBottom: 12,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      elevation: 2,
    },
    productHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 4,
    },
    productName: { fontSize: 16, fontWeight: "600", color: "#1A1A1A" },
    productPrice: { fontSize: 16, fontWeight: "600", color: "#6B48FF" },
    productCategory: { fontSize: 14, color: "#A0A0A0", marginBottom: 4 },
    statusContainer: { flexDirection: "row", justifyContent: "space-between" },
    stockStatus: { fontSize: 14, fontWeight: "500" },
    availability: { fontSize: 14, color: "#666" },
    emptyContainer: { flex: 1, justifyContent: "center", alignItems: "center" },
    emptyText: { fontSize: 18, color: "#A0A0A0", marginTop: 16 },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "center",
      alignItems: "center",
    },
    modalContent: {
      backgroundColor: "#FFF",
      borderRadius: 8,
      width: "90%",
      maxHeight: "80%",
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      padding: 12,
      borderBottomWidth: 1,
      borderBottomColor: "#E0E0E0",
    },
    modalTitle: { fontSize: 20, fontWeight: "700", color: "#1A1A1A" },
    modalBody: { padding: 12 },
    filterSection: { marginBottom: 16 },
    filterSectionTitle: { fontSize: 16, fontWeight: "600", marginBottom: 8 },
    filterButtons: { flexDirection: "row", flexWrap: "wrap" },
    filterButton: {
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: "#6B48FF",
      marginRight: 8,
      marginBottom: 8,
    },
    filterButtonActive: { backgroundColor: "#6B48FF" },
    filterButtonText: { fontSize: 14, color: "#6B48FF" },
    filterButtonTextActive: { color: "#FFF", fontWeight: "600" },
    resetButton: {
      backgroundColor: "#FFF",
      padding: 12,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: "#6B48FF",
      alignItems: "center",
      margin: 12,
    },
    resetButtonText: { fontSize: 16, color: "#6B48FF", fontWeight: "600" },
  });

  export default styles